services:
  - type: web
    name: skill-sharp-backend
    env: node
    plan: free
    region: oregon
    branch: main
    rootDir: backend  # If your backend code is in a 'backend' folder
    # rootDir: .     # Use this if backend code is in root
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: skill-sharp-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 30d
      - key: FRONTEND_URL
        value: https://skill-sharp365.vercel.app
